name: Analytics Export

on:
  schedule:
    - cron: '0 2 * * *'  # Ежедневно в 2:00
  workflow_dispatch:
    inputs:
      analytic_keys:
        description: 'Comma-separated list of analytic keys to export'
        required: false
        default: ''

jobs:
  export-analytics:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export analytics
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        run: |
          echo "🔄 Starting analytics export..."
          python scripts/planfix_export_analytics.py
          echo "✅ Analytics export completed"

      - name: Get analytics list (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        run: |
          echo "📋 Getting analytics list..."
          python scripts/planfix_get_analytics_list.py
          echo "✅ Analytics list retrieved" 