name: Export Data and Send Reports

on:
  schedule:
    # Летнее время (март-октябрь): 17:00 UTC = 19:00 CEST
    - cron: '0 17 * 3-10 1-5'  # Март-Октябрь: 19:00 по варшавскому времени
    # Зимнее время (октябрь-март): 18:00 UTC = 19:00 CET
    - cron: '0 18 * 1-2,11-12 1-5'  # Январь-Февраль, Ноябрь-Декабрь: 19:00 по варшавскому времени
  workflow_dispatch:  # Для ручного запуска

jobs:
  export-and-reports:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export clients from Planfix
        id: export-clients
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        run: |
          echo "Starting clients export..."
          python -c "import os; print('Environment variables:', {k: v[:3] + '...' if v else None for k, v in os.environ.items() if k.startswith(('PLANFIX_', 'SUPABASE_'))})"
          if ! python -u scripts/planfix/planfix_export_clients.py; then
            echo "::error::Failed to export clients"
            exit 1
          fi

      - name: Export orders from Planfix
        id: export-orders
        if: steps.export-clients.outcome == 'success'
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        run: |
          echo "Starting orders export..."
          python -c "import os; print('Environment variables:', {k: v[:3] + '...' if v else None for k, v in os.environ.items() if k.startswith(('PLANFIX_', 'SUPABASE_'))})"
          if ! python -u scripts/planfix/planfix_export_orders.py; then
            echo "::error::Failed to export orders"
            exit 1
          fi

      - name: Export tasks from Planfix
        id: export-tasks
        if: steps.export-orders.outcome == 'success'
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        run: |
          echo "Starting tasks export..."
          python -c "import os; print('Environment variables:', {k: v[:3] + '...' if v else None for k, v in os.environ.items() if k.startswith(('PLANFIX_', 'SUPABASE_'))})"
          if ! python -u scripts/planfix/planfix_export_tasks.py; then
            echo "::error::Failed to export tasks"
            exit 1
          fi

      - name: Generate KPI report
        id: generate-kpi
        if: steps.export-tasks.outcome == 'success'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting KPI report generation..."
          echo "Environment variables:"
          echo "SUPABASE_CONNECTION_STRING: ${SUPABASE_CONNECTION_STRING:+set}"
          echo "SUPABASE_HOST: ${SUPABASE_HOST:+set}"
          echo "SUPABASE_DB: ${SUPABASE_DB:+set}"
          echo "SUPABASE_USER: ${SUPABASE_USER:+set}"
          echo "SUPABASE_PASSWORD: ${SUPABASE_PASSWORD:+set}"
          echo "SUPABASE_PORT: ${SUPABASE_PORT:+set}"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:+set}"
          echo "TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:+set}"
          
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "::error::Missing required Telegram configuration"
            exit 1
          fi
          
          if ! python -u scripts/reports/report_kpi.py; then
            echo "::error::Failed to generate KPI report"
            exit 1
          fi

      - name: Generate activity report
        id: generate-activity
        if: steps.generate-kpi.outcome == 'success'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting activity report generation..."
          echo "Environment variables:"
          echo "SUPABASE_CONNECTION_STRING: ${SUPABASE_CONNECTION_STRING:+set}"
          echo "SUPABASE_HOST: ${SUPABASE_HOST:+set}"
          echo "SUPABASE_DB: ${SUPABASE_DB:+set}"
          echo "SUPABASE_USER: ${SUPABASE_USER:+set}"
          echo "SUPABASE_PASSWORD: ${SUPABASE_PASSWORD:+set}"
          echo "SUPABASE_PORT: ${SUPABASE_PORT:+set}"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:+set}"
          echo "TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:+set}"
          
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "::error::Missing required Telegram configuration"
            exit 1
          fi
          
          if ! python -u scripts/reports/report_activity.py; then
            echo "::error::Failed to generate activity report"
            exit 1
          fi

      - name: Generate bonus report
        id: generate-bonus
        if: steps.generate-activity.outcome == 'success'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting bonus report generation..."
          echo "Environment variables:"
          echo "SUPABASE_CONNECTION_STRING: ${SUPABASE_CONNECTION_STRING:+set}"
          echo "SUPABASE_HOST: ${SUPABASE_HOST:+set}"
          echo "SUPABASE_DB: ${SUPABASE_DB:+set}"
          echo "SUPABASE_USER: ${SUPABASE_USER:+set}"
          echo "SUPABASE_PASSWORD: ${SUPABASE_PASSWORD:+set}"
          echo "SUPABASE_PORT: ${SUPABASE_PORT:+set}"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:+set}"
          echo "TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:+set}"
          
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "::error::Missing required Telegram configuration"
            exit 1
          fi
          
          if ! python -u scripts/reports/report_bonus.py; then
            echo "::error::Failed to generate bonus report"
            exit 1
          fi

      - name: Generate income report
        id: generate-income
        if: steps.generate-bonus.outcome == 'success'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting income report generation..."
          echo "Environment variables:"
          echo "SUPABASE_CONNECTION_STRING: ${SUPABASE_CONNECTION_STRING:+set}"
          echo "SUPABASE_HOST: ${SUPABASE_HOST:+set}"
          echo "SUPABASE_DB: ${SUPABASE_DB:+set}"
          echo "SUPABASE_USER: ${SUPABASE_USER:+set}"
          echo "SUPABASE_PASSWORD: ${SUPABASE_PASSWORD:+set}"
          echo "SUPABASE_PORT: ${SUPABASE_PORT:+set}"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:+set}"
          echo "TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:+set}"
          
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "::error::Missing required Telegram configuration"
            exit 1
          fi
          
          if ! python -u scripts/reports/report_income.py; then
            echo "::error::Failed to generate income report"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${{ secrets.TELEGRAM_CHAT_ID }}\",\"text\":\"❌ Export and Reports workflow failed at step: ${{ job.status }}\",\"parse_mode\":\"Markdown\"}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} 