name: Planfix Sync

on:
  schedule:
    # Запуск каждый будний день в 16:00 CET (15:00 UTC)
    - cron: '0 15 * * 1-5'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests psycopg2-binary python-telegram-bot
        
    - name: Sync clients
      run: python scripts/planfix_clients_to_supabase.py
      env:
        PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
        PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
        PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        
    - name: Sync orders
      run: python scripts/planfix_orders_to_supabase.py
      env:
        PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
        PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
        PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        
    - name: Sync tasks
      run: python scripts/planfix_tasks_to_supabase.py
      env:
        PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
        PLANFIX_TOKEN: ${{ secrets.PLANFIX_TOKEN }}
        PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        
    - name: Send KPI report
      run: python scripts/send_kpi_to_telegram.py
      env:
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} 