name: Report Income

on:
  workflow_dispatch:  # Только для ручного запуска

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Income Report
        id: generate-report
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Starting income report generation..."
          echo "Environment variables:"
          echo "SUPABASE_CONNECTION_STRING: ${SUPABASE_CONNECTION_STRING:+set}"
          echo "SUPABASE_HOST: ${SUPABASE_HOST:+set}"
          echo "SUPABASE_DB: ${SUPABASE_DB:+set}"
          echo "SUPABASE_USER: ${SUPABASE_USER:+set}"
          echo "SUPABASE_PASSWORD: ${SUPABASE_PASSWORD:+set}"
          echo "SUPABASE_PORT: ${SUPABASE_PORT:+set}"
          echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:+set}"
          echo "TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:+set}"
          
          # Check if all required variables are set
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "::error::Missing required Telegram configuration"
            exit 1
          fi
          
          # Run the script with debug output
          if ! python -u scripts/report_income.py; then
            echo "::error::Failed to generate income report"
            exit 1
          fi 