name: Send KPI to Telegram

on:
  schedule:
    # Летнее время (март-октябрь): 14:00 UTC = 16:00 CEST
    - cron: '0 14 * 3-10 1-5'  # Март-Октябрь: 16:00 по варшавскому времени
    # Зимнее время (октябрь-март): 15:00 UTC = 16:00 CET
    - cron: '0 15 * 1-2,11-12 1-5'  # Январь-Февраль, Ноябрь-Декабрь: 16:00 по варшавскому времени
  workflow_dispatch:  # Для ручного запуска

jobs:
  update-and-send:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update clients in Supabase
        id: update-clients
        run: |
          if ! python scripts/planfix_clients_to_supabase.py; then
            echo "::error::Failed to update clients"
            exit 1
          fi
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_USER_TOKEN: ${{ secrets.PLANFIX_USER_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

      - name: Update orders in Supabase
        id: update-orders
        if: steps.update-clients.outcome == 'success'
        run: |
          if ! python scripts/planfix_orders_to_supabase.py; then
            echo "::error::Failed to update orders"
            exit 1
          fi
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_USER_TOKEN: ${{ secrets.PLANFIX_USER_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

      - name: Update tasks in Supabase
        id: update-tasks
        if: steps.update-orders.outcome == 'success'
        run: |
          if ! python scripts/planfix_tasks_to_supabase.py; then
            echo "::error::Failed to update tasks"
            exit 1
          fi
        env:
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_USER_TOKEN: ${{ secrets.PLANFIX_USER_TOKEN }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

      - name: Send KPI to Telegram
        id: send-kpi
        if: steps.update-tasks.outcome == 'success'
        run: |
          if ! python scripts/send_kpi_to_telegram.py; then
            echo "::error::Failed to send KPI to Telegram"
            exit 1
          fi
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${{ secrets.TELEGRAM_CHAT_ID }}\",\"text\":\"❌ KPI workflow failed at step: ${{ job.status }}\",\"parse_mode\":\"Markdown\"}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
