name: Telegram KPI Command Dispatch

on:
  repository_dispatch:
    types: [telegram_command]

jobs:
  handle-telegram-command:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run KPI Bonus Report (premia_current)
        if: github.event.client_payload.command == 'premia_current'
        env:
          SUPABASE_CONNECTION_STRING: postgresql://${{ secrets.SUPABASE_USER }}:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_HOST }}:${{ secrets.SUPABASE_PORT }}/${{ secrets.SUPABASE_DB }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ github.event.client_payload.chat_id }}
        run: python scripts/report_bonus.py 