name: Test ZKL Fix

on:
  workflow_dispatch:
    inputs:
      test_month:
        description: 'Month to test (1-12)'
        required: true
        default: '6'
      test_year:
        description: 'Year to test'
        required: true
        default: '2025'

jobs:
  test-zkl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test ZKL calculation
      env:
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
      run: |
        python3 scripts/test_zkl_fix.py
        
    - name: Test KPI report generation
      env:
        SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
        SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
        SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
      run: |
        python3 scripts/report_kpi.py ${{ github.event.inputs.test_month }} ${{ github.event.inputs.test_year }} 